// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using parsing_Jrn_Ej.Data;

#nullable disable

namespace parsing_jrn_ej.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110080729_create_atm_transaksi")]
    partial class create_atm_transaksi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("parsing_Jrn_Ej.Models.AtmTransaksi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AtmId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atm_id");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime")
                        .HasColumnName("dibuat_pada");

                    b.Property<string>("JenisFile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jenis_file");

                    b.Property<string>("JenisTransaksi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jenis_transaksi");

                    b.Property<decimal?>("Jumlah")
                        .HasColumnType("numeric")
                        .HasColumnName("jumlah");

                    b.Property<string>("Lokasi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lokasi");

                    b.Property<string>("NamaAtm")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama_atm");

                    b.Property<string>("NoKartu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("no_kartu");

                    b.Property<string>("NoRef")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("no_ref");

                    b.Property<string>("NoRekening")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("no_rekening");

                    b.Property<int?>("NoTransaksi")
                        .HasColumnType("int")
                        .HasColumnName("no_transaksi");

                    b.Property<string>("OpCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("op_code");

                    b.Property<string>("PesanError")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pesan_error");

                    b.Property<decimal?>("Saldo")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo");

                    b.Property<string>("Struk")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("struk");

                    b.Property<string>("TerminalId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("terminal_id");

                    b.Property<DateTime?>("Waktu")
                        .HasColumnType("datetime")
                        .HasColumnName("waktu");

                    b.HasKey("Id");

                    b.ToTable("atm_transaksi");
                });
#pragma warning restore 612, 618
        }
    }
}
